### PR TITLE
fix(analytics): updated analytics to use angulartics

### PR DESCRIPTION
**Pull request by russelltaylor05**

### CODE REVIEW

**Comment by russelltaylor05** [comment]
@robinjoseph08 

- needs a rebase, but there was an issue with the shrinkwrap file. Not sure how to fix that part

**Comment by robinjoseph08** [comment]
I [took a stab at it](https://github.com/robinjoseph08/pokedextracker.com/pull/114/files) this weekend, and I think I got all the changes that you made. You definitely pushed me in the right direction with `angulartics2`.

And yeah, that janky `var _gaq = window._gaq || null;` crap seemed necessary. I don't know if there's a better way though.

**Comment by russelltaylor05** [comment]
@robinjoseph08 ok cool, Yeah I checked analytics and your data is looking a lot better. Now you can see sign up by source, check it out

https://analytics.google.com/analytics/web/#report/trafficsources-all-traffic/a45307701w114513976p119665183/

**Comment by robinjoseph08** [comment]
cool, since this has already been implemented, i'll just close this pr 👍

**Pull request closed without merging**
