### PR TITLE
feat(routes): finalize routing

### LINKED ISSUE #30: Finalize routing
### why

instead of having `/tracker`, the home route would redirect you to your own dex to see, allowing anybody to go to any user's dex by going to the correct link

### notes

- change tracker route to be dynamic and pull from the username in the link
- if logged in, redirect from login, register, and home
- pull nav out of the app component and put it in each child component (login, register, tracker) since the home page won't have it

### LINKED ISSUE #40: Restructure app to remove nav from home
slack for ios upload

### PR DESCRIPTION
**Pull request by robinjoseph08**
ヘ(￣ω￣ヘ)

### what
* moved nav down to login, register, and tracker components, removing it from home
* if logged in, redirect from home, login, and register to your tracker page
* change from `/tracker` -> `/u/:username` and load correct basic info (no captures yet) of the user

### notes
* this does not handle user 404's. that will be handled in #43
* by moving nav, it messed up the flexbox configuration, so that needs to be fixed. i tried fixing it and other things broke so i'll leave that to you :)
* when a tracker page is loading, i'm hiding the entire dex component (to simulate loading and because it'll err otherwise), causing some weird stuff (the info component starts at the top). when you add the loading gif, that'll be the time to fix that
* the way it's set up right now, it would be possible to have multiple loading states (show the header after the user is done loading, then show the pokemon, then show the captures, etc). i don't know if that's desired or if you just wanna have one "loading state" that ends when everything is done loading. what do you think?

fixes #30 
fixes #40

### CODE REVIEW

**Comment by ami** [comment]
1 Q: should signing out route you back to /home? right now it shows you the "view only" version of your own tracker, which is slightly confusing.

re: gifs, i'd prefer to just have one gif that loads when everything's done. no point in using any one part of the tracker without any of the others.

**Comment by robinjoseph08** [comment]
technically, it just leaves you on the page you were on (regardless of whether it's your tracker or not), but i can see it maybe being better to redirect home. i dont have a preference.

cool, then we'll do one gif :+1:

**Comment by ami** [comment]
ic. it might be less confusing once we actually have a separate design for "viewing" someone's dex, and maybe it'll be more clear. we'll see. begs the question if we should have some sort of indication of "viewing" vs. "editing". cause you could also be signed in but be viewing someone else's dex..

anyways lgtm!

**Comment by robinjoseph08** [comment]
hmm good point. yeah, we might need that distinction.

do you wanna wait to merge this until you can fix the styles or do you wanna do that in a separate PR?

**Comment by ami** [comment]
Let's merge this one and I'll rebase my homepage PR and fix it there.

**Pull request merged**
