### PR TITLE
feat(box): mark/unmark entire box

### PR DESCRIPTION
**Pull request by ami**
fixes https://github.com/robinjoseph08/pokedextracker.com/issues/16

needs to be connected to the back-end. i'm thinking that it will change from "mark all" to "unmark all" if you have the whole box already. also, while the request is happening, it'd be cool to disable the button and replace the content with a spinner of some sort?

### CODE REVIEW

**Comment by robinjoseph08** [comment]
@ami updated! ⊂(・ヮ・⊂)

* add functionality to the button
* change to "unmark all" if all of the pokemon are caught
* disable the button when the mark all request is loading
* insert the font awesome spinner in the button while loading
  * this needs to be styled
  * it's a bit jittery on my computer, but everything is laggy on my computer right now... and idk how it will fare once deployed

also... the update to api i had to make kinda broke things in prod... so once this is merged, we'll either need to deploy this or revert the api until we deploy this...

**Comment by ami** [comment]
@robinjoseph08 LOL wth?? i tested that it works (it's pretty fast and not laggy for me!), so you should go ahead and revert API so prod is fixed. i should be fine updating the styles without the actual implementation.

**Comment by robinjoseph08** [comment]
@ami reverted! ^_^

and good to hear about the lag. time to restart my computer :+1:

**Comment by ami** [comment]
@robinjoseph08 updated!!

**Comment by ami** [comment]
also this was totes easy. we should do this on dashbooaorrdddd

**Comment by robinjoseph08** [comment]
looks siiiick :+1: 

and fo sho. we can do it on friday!

**Comment by ami** [comment]
yayyyy fridaysss

**Pull request merged**
