### PR TITLE
fix(tracker): loading text

### PR DESCRIPTION
**Pull request by ami**
¯\_༼ ಥ ‿ ಥ ༽_/¯

fixes https://github.com/robinjoseph08/pokedextracker.com/issues/22

i can't get the loading part in `info.ts` to work lol. fix itttt

### CODE REVIEW

**Comment by robinjoseph08** [comment]
@ami it's now hooked up! ...but the entire info panel disappears while it loads lol. fix itttt

**Comment by ami** [comment]
@robinjoseph08 fixeddd

**Comment by robinjoseph08** [comment]
what do you think about adding `LOADING...` to the info panel too? the fact that everything disappears a bit weird to me. or maybe just make the `.info-location` disappear and leave the name, icon, and number in the header (since that part doesn't need to load)?

**Comment by ami** [comment]
i tried that but it looked even weirder b/c it's only there for such amount of time. didn't realize the header doesn't need to load - i think that'd be ideal. i'll try that!

**Comment by ami** [comment]
updateddd

**Comment by robinjoseph08** [comment]
:boom: looks bootiful

**Pull request merged**
