### PR TITLE
chore(deps): upgrade angular beta.12 -> beta.15 and other deps

### PR DESCRIPTION
**Pull request by robinjoseph08**
༼ (´・ｪ・`) ༽

updating for the sake of updating. you should `npm i` and run it, just make sure it still works!

### CODE REVIEW

**Comment by ami** [comment]
is that...... [a llama](https://www.youtube.com/watch?v=bHNczNvOnGc)?????!?!?

`npm i` errors on this for me and then `npm start` doesn't work after that:
screenshot 2016-04-23 22 58 23

**Comment by robinjoseph08** [comment]
lolol i wanted to add a duck one too but they didn't have one!

is that the only line that was outputted? what's the output of `node -v` and `npm -v`?

**Comment by ami** [comment]
`v5.9.0` and `3.7.3`. it would run for like a few minutes with the little progress bar thing but then error with that one line.

**Comment by robinjoseph08** [comment]
thats super weird that thats the only line that was outputted...

try `npm cache clean` and then `rm -rf node_modules` and `npm i` again

**Comment by ami** [comment]
nope same thing 😢

**Comment by robinjoseph08** [comment]
hmmmmmmmmmm

try `npm I npm -g` and then try again ¯\\\_(ツ)_/¯

**Comment by ami** [comment]
noooppppe

**Comment by robinjoseph08** [comment]
butttts. if you checkout master, does it work just fine?

**Comment by ami** [comment]
hmm. `npm i` worked on master and then i just switched back to this branch and ran it. lol 

lgtm? ¯\_(ツ)_/¯

**Comment by robinjoseph08** [comment]
lol did you rerun `npm i` when you switched back? cause if not, you weren't testing the actual upgrades hahaha

**Comment by ami** [comment]
lol dang it. same error. THIS IS DUMB

**Comment by robinjoseph08** [comment]
hmm thats interesting though. it means something on this branch is breaking it. ill look into it

**Comment by robinjoseph08** [comment]
closing this since it's now on [rc.4](https://github.com/angular/angular/blob/master/CHANGELOG.md) and beta.15 is now out of date. ill make another one and upgrade it all the way up and hopefully that one wont have issues

**Comment by ami** [comment]
lolol maybe it'll work now that i've upgraded my OS!!! haha

**Pull request closed without merging**
