### PR TITLE
feat(dex): added serebii link

### PR DESCRIPTION
**Pull request by ashcoding**
Hi there. Love the project. Just wanted to add a suggestion.

I seriously love checking for info at serebii over bulbapedia. I use it often to find information on breeding, catching, held item and more.

screen shot 2016-07-12 at 7 35 37 pm

This is an ugly PR but it's here just to make it work. Let me know if what you think. I'm fine if it's declined. Even better if you could point me in the right direction to make this happen.

I assume a PR is better than creating an issue to suggest a feature. 😄

### CODE REVIEW

**Comment by robinjoseph08** [comment]
Hey @ashcoding!

Thanks for the contribution! We've actually gotten this request a few times, but just haven't gotten around to it, so we really appreciate you taking the time!

Your code is actually just fine, and I really appreciate how you kept the style of the surrounding code. But to keep consistency with how we have `bulbapedia_url` setup, ideally [the API](https://github.com/robinjoseph08/api.pokedextracker.com) returns that URL, and we just assign it to `this.serebii_url` instead of generating it on the frontend. I went ahead and made [an issue](https://github.com/robinjoseph08/pokedextracker.com/issues/138) for that. Feel free to take a stab at it, but if you don't want to, we'll probably get to it this weekend.

As for the design of it, I'll defer the final say to @ami since she's the one that has made the rest of the site look polished. We were thinking instead of stacking the two buttons on top of each other, to actually split the button into two and have them side by side.

In terms of action items so we can get this PR merged, here's what should be done:

- [ ] You or me - update the API to return `serebii_url`
- [ ] You - update your commit to use the new response to set `this.serebii_url`
- [ ] @ami - add another commit to this PR with the appropriate styles

What do you think? I want to make sure you have the opportunity to contribute as much as you want, but if you want to hand it off, we'll make sure this feature gets deployed!

**Comment by ashcoding** [comment]
Thanks for the fast reply @robinjoseph08.

I'll take a [STAB](http://bulbapedia.bulbagarden.net/wiki/Same-type_attack_bonus) at it. Probably the weekend or maybe earlier when I can spare some time.

I'll do the following:

- Update the API to return ```serebii_url``` (Using left-pad for the padding of `0`s) and create a new PR
- Update this PR to consume ```this.serebii_url```
- I'll remove the changes done in ```app/views/info.html``` and leave it to you and @ami to either advise me on what to do or for you to implement it

**Comment by ashcoding** [comment]
Both PRs (this and https://github.com/robinjoseph08/api.pokedextracker.com/pull/32) are ready to be reviewed.

**Comment by robinjoseph08** [comment]
Awesome, I just deployed your change for the API, and it looks like the new param is being sent correctly. Your commit in this PR looks just fine, so now I'll pass it to @ami to take it from here! Thanks again for your help and cooperation with us! We really appreciate it!

**Comment by ashcoding** [comment]
No problem. Just let me know what's needed for me to get this PR going for the front-end.

**Comment by ami** [comment]
thanks for the contribution @ashcoding! i will get to this as soon as i can - nothing else needed on your side :)

**Comment by ami** [comment]
@ashcoding on second thought, let's just merge this and i'll add the style fixes in a separate PR - we just won't deploy the front-end until that other PR is in. @robinjoseph08 can you give an LGTM?

**Comment by robinjoseph08** [comment]
LGTM! Merging!

**Pull request merged**
